config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    scope module: :topics do
      resources :posts, except: [:new, :create]
    end
  end
  
  devise_for :users, controller: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#home'

  get 'posts/new', to: 'topics/posts#new', as: 'new_post'
  post 'posts', to: 'topics/posts#create', as: 'create_post'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_uniqueness_of :slug
  validates_presence_of :title, :slug
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_initialize :set_defaults

  validates_presence_of :first_name, :last_name 
  validates :username, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+([a-zA-Z]|\d)*\Z/ }

  has_many :posts

  def full_name
    self.first_name + " " + self.last_name
  end

  private

    def set_defaults
      self.role ||= 'student'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  before_action :set_topic, except: [:new, :create]
  def index
    @posts = @topic.posts
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    post = Post.new(post_params)
    # post.user_id = current_user.id

    if post.save
      redirect_to topic_post_path(topic_id: post.topic_id, id: post), notice: 'Your post was successfully published.'
    else
      render :new
    end
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :topic_id, :user_id)
    end

    def set_topic
      @topic = Topic.friendly.find(params[:topic_id])
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update]

  def index
    @topics = Topic.all
  end

  def show
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    
    if @topic.save
      redirect_to topic_path(@topic), notice: 'Topic was successfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to topic_path(@topic), notice: 'Your topic was successfully updated.'
    else
      render :edit, notice: 'There was an error processing your request'
    end
  end

  private

    def topic_params
      params.require(:topic).permit(:title,
                                    posts_attributes: [:id, :title, :content, :topic_id]
                                    )
    end

    def set_topic
      @topic = Topic.friendly.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dailysmarty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_alerts.html.erb
<p class"notice"><%= notice %></p>
<p class"alert"><%= alert %></p>

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>

  <%= f.text_field :title %>
  <%= f.submit 'Save' %>

<% end %>

app/views/topics/_topic.html.erb
<div>
  <%= link_to topic.title, topic %>
</div>

app/views/topics/edit.html.erb
<%= render partial: 'form', locals: { source: 'edit' } %>

app/views/topics/index.html.erb
<%= render @topics %>

app/views/topics/new.html.erb
<%= render partial: 'form', locals: { source: 'new' } %>

app/views/topics/posts/index.html.erb
<% @posts.each do |post| %>
  <div><%= link_to post.title, topic_post_path(topic_id: @topic, id: post) %></div>
  <div><%= post.content %></div>
  <div><%= post.user.username %></div>
<% end %>

<%= link_to "New Post", new_post_path(topic_id: @topic.id) %>

app/views/topics/posts/new.html.erb
<%= form_tag create_post_path, method: 'post' do %>

  <%= text_field_tag :title %>
  <%= text_field_tag :content %>
  <%= collection_select(:post, 
                        :topic_id, 
                        Topic.all, 
                        :id, 
                        :title,
                        { selected: (params[:topic_id] if params[:topic_id])}) 
  %>

  <%= submit_tag 'Save' %>

<% end %>

app/views/topics/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.topic.title %></p>
<p><%= @post.user.full_name %></p>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>